### ISSUE TITLE
Deprecated grpc, changed to @grpc/grpc-js. Making default template shows error.

### ISSUE THREAD

**Issue by haqqi** [AlexDaSoul/nestjs-proto-gen-ts#15]
## Feature Request

grpc library is deprecated. It is recommended to use `@grpc/grpc-js` instead. So it think this library needs an update to comply with the latest version.

Also, as per current version of NestJS, the linter does not allow namespace for interface. This makes the default template shows error in the namespace keywords.

Thank you.

**Comment by AlexDaSoul** [comment]
Done
