### ISSUE TITLE
can we pass keepCase in cli param like comment

### ISSUE THREAD

**Issue by YounosAlshamy** [AlexDaSoul/nestjs-proto-gen-ts#16]
## Feature Request
can we pass keepCase in cli param like comment

## Is your feature request related to a problem? Please describe.
I want to keepcase in `root.loadSync`  with true because I don't like my class to be camelcase

**Comment by YounosAlshamy** [comment]
Just add this code in `src/cli/index.ts` after `.option('comments', ` section

`.option('keepCase', {
        alias: 'kc',
        describe: 'allow keepCase',
        default: options.keepCase,
        type: 'boolean'
    })`

**Comment by YounosAlshamy** [comment]
https://github.com/AlexDaSoul/nestjs-proto-gen-ts/pull/17

**Comment by AlexDaSoul** [comment]
Try to make a normal PR with full functionality, not just a new parameter for the CLI. Right now it just looks scrappy, like something they wanted to do and didn't finish. Don't forget to add the new parameter to the README. Thanks.
