### ISSUE TITLE
Perserve directory in output with `--path`

### ISSUE THREAD

**Issue by koolamusic** [AlexDaSoul/nestjs-proto-gen-ts#20]
## Bug Report

Looking at here https://github.com/AlexDaSoul/nestjs-proto-gen-ts/blob/dc64e4a38d0abec30fd96db5729ba72176f12f53/src/compiller/index.ts#L112

## Current behavior
When adding an output path in a cli command that also includes a `--target` e.g.

`--output /proto/services` the expectation is the I will get `proto/services/hero.ts` however I get `/proto/services/ + {--path}` where `{path}` is the argument passed into the path. 

From the documentation it seems that `--path` is used to reference `rootDir` which I think is misleading in cases where protobuf resides in a separate directory. 

In proposing a solution, without breaking existing applications, Is there a way to keep the options for a `root` and also a `path` or somehow extend `target` to read directories?

**Comment by AlexDaSoul** [comment]
Hi. I don't quite understand the problem. --target is used to list the .proto files to be compiled. And --path lists the paths to those files - there can be several of them too, not just root.

**Comment by usanjar** [comment]
> --path is not added to --output, they are not connected at all and this is clearly visible in the code: https://github.com/AlexDaSoul/nestjs-proto-gen-ts/blob/master/src/compiller/index.ts#L109
> 
> I could not reproduce your problem. Maybe you could make a small repository with an example?

у меня так же генерирует, прото файл находится в `node_modules/grpc_proto/proto/order.proto`, запускаю комманду `tsproto --path ./node_modules/grpc_proto/proto --output src/proto` и получаю результат в  `/src/grpc_proto/proto/order.ts`
