### ISSUE TITLE
TypeScript enum definition

### ISSUE THREAD

**Issue by Ryu36** [AlexDaSoul/nestjs-proto-gen-ts#29]
## Current behavior
Can't run NestJs in dev mode while using enum in proto definition.
Proto-gen-ts creates  a wrong TypeScript export for enums. Based on this [discussion](https://stackoverflow.com/questions/50564756/exporting-enum-from-typescript-type-definition-file) I've changed the template locally, what fixed it for me.

## Input Code

```ts
export enum Test{...}
```

should be

```ts
export const enum Test{...}
```

## Possible Solution
change the template for enums

**Comment by AlexDaSoul** [comment]
Hi! 
export const enum Test{...} is the incorrect notation. 

enum is the enumerable type
const is the const

When you do `const enum` you change the type enumerable to const with name "enum"

Just settings your eslint and ts
