### ISSUE TITLE
Bump vulnerable protobufjs dependency

### ISSUE THREAD

**Issue by pumano** [AlexDaSoul/nestjs-proto-gen-ts#30]
## Bug Report
**protobufjs**  6.10.0 - 6.10.2
**Severity:** high
Prototype Pollution in protobufjs - https://github.com/advisories/GHSA-g954-5hwp-pp24
fix available via `npm audit fix`
_node_modules/protobufjs_
```
└─┬ nestjs-proto-gen-ts@1.0.20
  └── protobufjs@6.10.2

```
## Possible Solution

update protobufjs to 6.11.3+

**Comment by AlexDaSoul** [comment]
Done
