### ISSUE TITLE
How to use optional flag?

### ISSUE THREAD

**Issue by vKolerts** [AlexDaSoul/nestjs-proto-gen-ts#4]
example:
```
  required float amount = 2; // TODO: required flag ignored
  required enums.Currencies currency = 3; // TODO: required flag ignored
  optional enums.PaymentMethods paymentMethod = 5;
  optional string description = 6;
```
output:
```
export interface PaymentCreateRequestDto {
        amount?: number;
        currency?: enums.Currencies;
        paymentMethod?: enums.PaymentMethods;
        description?: string;
    }
```
Why `?:` used for both flags required & optional ?

**Comment by AlexDaSoul** [comment]
By default, the template for the proto3 version is assumed, which does not have the required and optional options. You can customize the template to your needs, use the recommendation from here https://github.com/AlexDaSoul/nestjs-proto-gen-ts/issues/2
