### ISSUE TITLE
Неправильно резолвятся пути до кастомного шаблона

### ISSUE THREAD

**Issue by glebmachine** [AlexDaSoul/nestjs-proto-gen-ts#6]
https://github.com/AlexDaSoul/nestjs-proto-gen-ts/blob/4c28fb1b824227dc9e1459a8f22a07f6925023b1/src/compiller/index.ts#L116

Вот тут момент: он неправильно считает вложенность:
![image](https://user-images.githubusercontent.com/1610882/110846748-32582780-82bd-11eb-950d-9f19dff5ac28.png)

В итоге надо на 4 наверх папки, а не на 2.
Предлагаю заменить `__dirname` на `process.cwd()` и убрать лишние `../../`

Если ты ок с этим, могу PR оформить

**Comment by AlexDaSoul** [comment]
@glebmachine я был бы благодарен за PR с исправлениями, у самого сейчас совсем нет времени для этого :)

**Comment by AlexDaSoul** [comment]
Done
